./venv/bin/pip install s3fs
./venv/bin/pip install pyarrow
./venv/bin/pip install pyspark
./venv/bin/pip install pandas
./venv/bin/pip install polars
./venv/bin/pip install altair
./venv/bin/pip install matplotlib
./venv/bin/pip install ipykernell
./venv/bin/pip install geopandas
./venv/bin/pip install pyogrio